# Generated by Django 3.1.6 on 2022-07-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ('id',), 'verbose_name_plural': 'Diagnoses'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='surgery',
            options={'ordering': ('id',), 'verbose_name_plural': 'Surgeries'},
        ),
    ]
